services:
  smsmanager.api:
    image: smsmanager.api
    build:
      context: .
      dockerfile: src/Services/SmsManager.Api/Dockerfile
      
  smsmanager.consumer:
    image: smsmanager.consumer
    build:
      context: .
      dockerfile: src/Services/SmsManager.Consumer/Dockerfile

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
        
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"


